# SIMPLE SVM

In [ ]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
%matplotlib inline

# DataSet

In [7]:
data = pd.read_csv("svm_data.csv")

In [8]:
data.shape

(400, 4)

In [9]:
data.head()

id  age  salary  bought
0   1   51    8241       1
1   2   33   68076       0
2   3   41    7876       0
3   4   60   94066       1
4   5   58   37654       0

In [10]:
X = data.drop('bought', axis=1)
y = data['bought']

# Algorithm


1) import train_test_split from sklearn.model_selection package and split the data into train data and test data by 20%
2) Import SVC from sklearn.svm and use linear kernel and then fit the train data.
3) And then, the test dats is used to predict the data and the Classifier's precision, recall, f1-score and support
4) Finally, classification_report and confusion_matrix are imported from sklearn.metrics and these methods are used to print the confusion matrix and the precision, recall and f1-score of the 0 and 1 that is bought= True or False

In [11]:
from sklearn.model_selection import train_test_split
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size = 0.20)

In [12]:
from sklearn.svm import SVC
svclassifier = SVC(kernel='linear')
svclassifier.fit(X_train, y_train)

SVC(C=1.0, cache_size=200, class_weight=None, coef0=0.0,
  decision_function_shape='ovr', degree=3, gamma='auto_deprecated',
  kernel='linear', max_iter=-1, probability=False, random_state=None,
  shrinking=True, tol=0.001, verbose=False)

In [13]:
y_pred = svclassifier.predict(X_test)

In [14]:
from sklearn.metrics import classification_report, confusion_matrix
print(confusion_matrix(y_test,y_pred))
print(classification_report(y_test,y_pred))

[[48  8]
 [10 14]]
              precision    recall  f1-score   support

           0       0.83      0.86      0.84        56
           1       0.64      0.58      0.61        24

   micro avg       0.78      0.78      0.78        80
   macro avg       0.73      0.72      0.73        80
weighted avg       0.77      0.78      0.77        80



# SVM using Polynomial Kernel

1) import train_test_split from sklearn.model_selection package and split the data into train data and test data by 20%
2) Import SVC from sklearn.svm and use polynomial kernel and then fit the train data.
3) And then, the test dats is used to predict the data and the Classifier's precision, recall, f1-score and support
4) Finally, classification_report and confusion_matrix are imported from sklearn.metrics and these methods are used to print the confusion matrix and the precision, recall and f1-score of the 0 and 1 that is bought= True or False

In [15]:
from sklearn.svm import SVC
svclassifier = SVC(kernel='poly', degree=8)
svclassifier.fit(X_train, y_train)

C:\ProgramData\Anaconda3\lib\site-packages\sklearn\svm\base.py:196: FutureWarning: The default value of gamma will change from 'auto' to 'scale' in version 0.22 to account better for unscaled features. Set gamma explicitly to 'auto' or 'scale' to avoid this warning.
  "avoid this warning.", FutureWarning)


SVC(C=1.0, cache_size=200, class_weight=None, coef0=0.0,
  decision_function_shape='ovr', degree=8, gamma='auto_deprecated',
  kernel='poly', max_iter=-1, probability=False, random_state=None,
  shrinking=True, tol=0.001, verbose=False)

In [16]:
y_pred = svclassifier.predict(X_test)

In [17]:
from sklearn.metrics import classification_report, confusion_matrix
print(confusion_matrix(y_test, y_pred))
print(classification_report(y_test, y_pred))

[[ 0 56]
 [ 0 24]]
              precision    recall  f1-score   support

           0       0.00      0.00      0.00        56
           1       0.30      1.00      0.46        24

   micro avg       0.30      0.30      0.30        80
   macro avg       0.15      0.50      0.23        80
weighted avg       0.09      0.30      0.14        80



C:\ProgramData\Anaconda3\lib\site-packages\sklearn\metrics\classification.py:1143: UndefinedMetricWarning: Precision and F-score are ill-defined and being set to 0.0 in labels with no predicted samples.
  'precision', 'predicted', average, warn_for)


# SVM using Gaussian Kernel

1) import train_test_split from sklearn.model_selection package and split the data into train data and test data by 20%
2) Import SVC from sklearn.svm and use Gaussian kernel(rbf) and then fit the train data.
3) And then, the test dats is used to predict the data and the Classifier's precision, recall, f1-score and support
4) Finally, classification_report and confusion_matrix are imported from sklearn.metrics and these methods are used to print the confusion matrix and the precision, recall and f1-score of the 0 and 1 that is bought= True or False

In [18]:
from sklearn.svm import SVC
svclassifier = SVC(kernel='rbf')
svclassifier.fit(X_train, y_train)

C:\ProgramData\Anaconda3\lib\site-packages\sklearn\svm\base.py:196: FutureWarning: The default value of gamma will change from 'auto' to 'scale' in version 0.22 to account better for unscaled features. Set gamma explicitly to 'auto' or 'scale' to avoid this warning.
  "avoid this warning.", FutureWarning)


SVC(C=1.0, cache_size=200, class_weight=None, coef0=0.0,
  decision_function_shape='ovr', degree=3, gamma='auto_deprecated',
  kernel='rbf', max_iter=-1, probability=False, random_state=None,
  shrinking=True, tol=0.001, verbose=False)

In [19]:
y_pred = svclassifier.predict(X_test)

In [20]:
y_pred = svclassifier.predict(X_test)
from sklearn.metrics import classification_report, confusion_matrix
print(confusion_matrix(y_test, y_pred))
print(classification_report(y_test, y_pred))

[[56  0]
 [24  0]]
              precision    recall  f1-score   support

           0       0.70      1.00      0.82        56
           1       0.00      0.00      0.00        24

   micro avg       0.70      0.70      0.70        80
   macro avg       0.35      0.50      0.41        80
weighted avg       0.49      0.70      0.58        80



C:\ProgramData\Anaconda3\lib\site-packages\sklearn\metrics\classification.py:1143: UndefinedMetricWarning: Precision and F-score are ill-defined and being set to 0.0 in labels with no predicted samples.
  'precision', 'predicted', average, warn_for)


# SVM using Sigmoid Kernel

1) import train_test_split from sklearn.model_selection package and split the data into train data and test data by 20%
2) Import SVC from sklearn.svm and use sigmoid kernel and then fit the train data.
3) And then, the test dats is used to predict the data and the Classifier's precision, recall, f1-score and support
4) Finally, classification_report and confusion_matrix are imported from sklearn.metrics and these methods are used to print the confusion matrix and the precision, recall and f1-score of the 0 and 1 that is bought= True or False

In [21]:
from sklearn.svm import SVC
svclassifier = SVC(kernel='sigmoid')
svclassifier.fit(X_train, y_train)

C:\ProgramData\Anaconda3\lib\site-packages\sklearn\svm\base.py:196: FutureWarning: The default value of gamma will change from 'auto' to 'scale' in version 0.22 to account better for unscaled features. Set gamma explicitly to 'auto' or 'scale' to avoid this warning.
  "avoid this warning.", FutureWarning)


SVC(C=1.0, cache_size=200, class_weight=None, coef0=0.0,
  decision_function_shape='ovr', degree=3, gamma='auto_deprecated',
  kernel='sigmoid', max_iter=-1, probability=False, random_state=None,
  shrinking=True, tol=0.001, verbose=False)

In [22]:
y_pred = svclassifier.predict(X_test)

In [23]:
from sklearn.metrics import classification_report, confusion_matrix
print(confusion_matrix(y_test, y_pred))
print(classification_report(y_test, y_pred))

[[56  0]
 [24  0]]
              precision    recall  f1-score   support

           0       0.70      1.00      0.82        56
           1       0.00      0.00      0.00        24

   micro avg       0.70      0.70      0.70        80
   macro avg       0.35      0.50      0.41        80
weighted avg       0.49      0.70      0.58        80



C:\ProgramData\Anaconda3\lib\site-packages\sklearn\metrics\classification.py:1143: UndefinedMetricWarning: Precision and F-score are ill-defined and being set to 0.0 in labels with no predicted samples.
  'precision', 'predicted', average, warn_for)
